resolver: ghc-8.0.2

packages:
- '../haxbase'
- '../haxpile'
- '.'

extra-deps:
- ghc-paths-0.1.0.9

dump-logs: all
install-ghc: true
compiler-check: newer-minor
allow-newer: true
allow-different-user: true

explicit-setup-deps:
  "*": true
