resolver: ghc-8.0.2

packages:
- '../haxbase'
- '../haxpile'
- '.'

dump-logs: all
compiler-check: newer-minor
allow-newer: true

explicit-setup-deps:
  "*": true

extra-deps:
- text-1.2.2.1
